### ISSUE TITLE
ExecutorServiceFuturePool fatal exceptions silently leave dangling Futures

### ISSUE THREAD

**Issue by gianm** [twitter/util#100]
When a FuturePool task throws a fatal exception (like an OOME), the task exits silently and the future never resolves. I think this is because apply tries to update its promise with Try(f), but Try(f) doesn't catch fatal exceptions in f, and so they bubble up and kill the runnable in the underlying executor service. Nothing is logged and the promise is never updated.

Code showing the behavior:

```scala
val pool = FuturePool.unboundedPool
val future = pool {
  throw new OutOfMemoryError()
}
Await.result(future) // blocks forever, silently
```

**Comment by vkostyukov** [comment]
I believe it was fixed in https://github.com/twitter/util/commit/01bf9d03aa0fac6907a85fd66c3050a04e2f3c55. Perhaps the test case from the first comment works now. Should we close it?

**Comment by evnm** [comment]
That's correct, @vkostyukov. I must've forgotten to close this ticket after merging the fix.

**Comment by vkostyukov** [comment]
Thanks @evnm!
