### ISSUE TITLE
Event[T]() creates non-threadsafe Event instance

### ISSUE THREAD

**Issue by sirmax** [twitter/util#101]
[`Event[T]()`](https://github.com/twitter/util/blob/192a134/util-core/src/main/scala/com/twitter/util/Event.scala#L284) creates an instance that maintains a list of registered witnesses in `@volatile var registerrs`. The updates to this var are neither atomic nor synchronized. As a result adding/closing a witness is not guaranteed to execute successfully.

Here's a sample implementation that I currently use instead:
```
  def event[A](): Event[A] with Witness[A] = new Event[A] with Witness[A] {
    private type W = Witness[A]
    private[this] val witnesses = new AtomicReference(Vector.empty[W])

    @tailrec private def cas(f: Vector[W] => Vector[W]): Unit = {
      val old = witnesses.get
      if (!witnesses.compareAndSet(old, f(old))) cas(f)
    }

    def register(w: Witness[A]) = {
      cas(_ :+ w)
      Closable.make { _ => cas(_.filterNot(_ eq w)); Future.Unit }
    }

    def notify(note: A) = synchronized { witnesses.get.foreach(_.notify(note)) }
  }
```

**Comment by vkostyukov** [comment]
Can we closed it based on [this commit](https://github.com/twitter/util/commit/3b0ebef10dcb0f0ceca1cd36920a3d23f5fe3846)?

**Comment by sirmax** [comment]
@vkostyukov sure! I'm closing it now.
