### ISSUE TITLE
util-eval refers to classes that are removed or deprecated in scala 2.11.x

### ISSUE THREAD

**Issue by richardclose** [twitter/util#105]
The issue is with util-eval/src/main/scala/com/twitter/util/Eval.scala, line 81:

    classPathOfClass("scala.ScalaObject")

This fails because ScalaObject has been removed, after being deprecated in 2.10.

Likewise, line 75:

    classPathOfClass("scala.tools.nsc.Interpreter")

refers to a class that is deprecated in 2.11.

(It's a bit odd that that this wasn't flagged by the unit tests)

**Comment by koertkuipers** [comment]
do i understand it correctly that util-eval will be made available for 2.11?
thats good news

i would be curious to know what other configuration mechanisms are preferred over util-eval. i did not realize it had fallen out of favor. we use it extensively for runtime compilation of classes...

thanks

**Comment by mosesn** [comment]
@koertkuipers we generally suggest that folks use the flags API instead.  It can be found in util-app, and it's described in the TwitterServer [docs][0].  If you're using flags, we generally recommend that you use TwitterServer.

[0]: http://twitter.github.io/twitter-server/Features.html#flags

**Comment by koertkuipers** [comment]
@mosesn 
i assume you already fixed util-eval up for scala 2.11, because i got the tests for it to run just fine in with one change in Eval.scala:
```
   private lazy val libPath = try {
-    classPathOfClass("scala.ScalaObject")
+    classPathOfClass("scala.AnyVal")
   } catch {
     case e: Throwable =>
       throw new RuntimeException("Unable to load scala base object from classpath (scala-library jar is missing?)", e)
```

**Comment by travisbrown** [comment]
@koertkuipers Yep, see [this commit](https://github.com/twitter/util/commit/84b9fa50916b496f71d2fd9b0cbb34f191b8a51f) in `develop`.

**Comment by koertkuipers** [comment]
great! i was looking on the wrong branch :(
glad to see its back. if it no longer has importance inside twitter i will
look around for alternatives (scala Toolbox comes to mind) but for now we
love this tool to run quick jobs from text files (in scalding and spark),
and for Scala DSL config files, which we use extensively (i still like it
way better than json or yaml).

happy to help out next time it needs to get migrated.

best, koert
