### ISSUE TITLE
RichU64String.toU64Long "parses" single digit negative numbers

### ISSUE THREAD

**Issue by evanj** [twitter/util#107]
This is extremely unimportant and may even "not a bug", but I was surprised when I did:

```scala
val longVal = "-1".toU64Long
```

In this case, `longVal` is `255`. Seems to me like this should probably throw `NumberFormatException`, since it isn't a valid unsigned 64-bit string? Other example values that return numbers:

-f
-f00
10-f00

I'm happy to submit a patch if that makes sense.

**Comment by vkostyukov** [comment]
Hey @evanj! Sorry for the long delay. Are you stil interested in submitting a PR?

**Comment by mosesn** [comment]
We don't have the bandwidth for this now, and it seems like @evanj doesn't have the time to work on this anymore, but I think this is a solid starter issue for anyone who wants to get involved in the project.

**Comment by mirokuratczyk** [comment]
This was resolved and should be closed: b3fe8f767ec5e5e2038e838d65c24f3ae78616cb 😄

**Comment by mosesn** [comment]
@mirokuratczyk good point!  totally forgot he had already fixed it, thanks @evanj!

**Comment by evanj** [comment]
Oh yeah me too. I think I filed this before I knew how anything worked at Twitter. Thanks!
