### ISSUE TITLE
What's the right pattern to crash process on certain exceptions in a FuturePool?

### ISSUE THREAD

**Issue by anshumans** [twitter/util#123]
I have a finagle service, and I want to be able to crash the process on certain exceptions that might fire in a FuturePool.  What's the right pattern to do this?

**Comment by mosesn** [comment]
Have you looked at [Monitors][0]?

[0]: https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Monitor.scala#L88

**Comment by anshumans** [comment]
I was taking a look at that.  Are there examples of how to use them?  Should I be wrapping the Monitor around the body of my FuturePool block?

**Comment by anshumans** [comment]
Also, it seems that by throwing an exception in my monitor will only cause the RootMonitor to handle it instead rather than crash the process.

**Comment by mosesn** [comment]
Have you considered writing a Monitor which calls System.exit?  It won't fall through to RootMonitor in that case.

**Comment by anshumans** [comment]
Yeah, that was going to be a last resort.  Generally calling System.exit is bad form :)  That's why I wanted to see if there's a better way of gracefuly shutting down my finagle server, but it doesn't seem like there is.

**Comment by mosesn** [comment]
@anshumans you could exit normally if you wanted . . . but you're going to have to write code to gracefully shut down, the same way as normal (ie /admin/shutdown in TwitterServer).  We don't have a special case for FuturePool.

Could you elaborate on what you were hoping we would have?

**Comment by anshumans** [comment]
I just wanted to check if there was anything I had to do specifically with the FuturePool to shut it down.  When shutdown my finagle thrift server, there were still a bunch of FuturePool.unbounded threads still sitting around, which was preventing the process from exiting.

**Comment by mosesn** [comment]
@anshumans the FuturePool's threads are all [daemon threads][0], so I don't think that's what's preventing your process from exiting.  That seems to be a separate problem from crashing your program when you get an exception in your FuturePool though . . . are these two separate problems that you have?  Could you elaborate on the problematic situation you're getting into?

[0]: https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/FuturePool.scala#L43

**Comment by anshumans** [comment]
Sorry, I should've been more clear - you're right, my issue with shutting down my Finagle server not shutting down the process is a separate problem.  My original question was really about what the right way was to crash the process if an exception got fired within a FuturePool, and it sounds like the best way is to call System.exit either in a Monitor or in the onFailure callback.

**Comment by mosesn** [comment]
If you want to do a clean shutdown, and your TwitterServer is wired up properly, then hitting that endpoint is probably a good way to shut down too.  My assumption if there's a special exception that you want to crash on is that you think it would be unsafe to continue making progress (like if there is a really bad state that you have gotten into).

Please reopen if you have any further questions. I'm going to close this issue and comment on your finaglers post summing up what we've discussed.

Thanks for coming to ask, always happy to help.

**Comment by anshumans** [comment]
Awesome, thanks for all your help!
