### ISSUE TITLE
oh awesome, *another* logging API

### ISSUE THREAD

**Issue by fommil** [twitter/util#125]
can you please give some docs or an interface to route to SLF4J?

If this doesn't require anything fancier than "simply" (it's not) re-routing JUL to SLF4J a link to the relevant docs would be appreciated by many.

**Comment by mosesn** [comment]
Hey @fommil, I think the Logging api is just a thin wrapper around jul, and I'm not sure of anywhere where we force you into using it.  What's the specific problem you're running into?

**Comment by fommil** [comment]
it's a transitive dep and if you're using it internally, I need to deal with that

**Comment by mosesn** [comment]
A transitive dependency on which module?  I'm sorry, but it's going to be much easier for me to help you if you can elaborate.

**Comment by fommil** [comment]
finagle and the whole twitter universe is using this logging API which means anyone using anything released by twitter needs to specially configure your logging API to go to SLF4J. I'm suggesting that you make this easy for people by providing some advice to do this. Reading your docs further, it looks like you're just using JUL, so I suggest you make that even clearer. The whole enterprise world uses SLF4J/logback. It beggars belief that twitter have made **yet another** API to cause us all a nightmare when debugging production issues.

**Comment by vkostyukov** [comment]
@mosesn, I think @fommil means that while it's still possible to use SLF4J in the user application it's not possible to configure Finagle servers/clients, TwitterServer & Co to use SLF4J. So, users end up having two different messages in the log (different logs?): one group of messages is from user code (from SLF4J) while another group of messages is from Finagle internals (from util-logging).

@fommil did I get you correctly?

**Comment by caniszczyk** [comment]
@fommil we always welcome contributions if you have ideas on how to make things better for you, it's fairly easy to contribute to our docs

https://github.com/twitter/finagle/blob/master/CONTRIBUTING.md#documentation

**Comment by fommil** [comment]
@vkostyukov yes, absolutely

@caniszczyk if you insist on writing **yet another logging framework** then writing documentation is definitely a cost that you should be made to pay yourself, :stuck_out_tongue: (along with being made to eat soap and write out 1000 times "I will not create another logging framework for the JVM").

**Comment by mariusae** [comment]
Hi @fommil, I understand your frustration. util-logging is there for historical reasons, that are now (and perhaps always were) outdated. We're hoping to obsolete util-logging in the medium-term future, probably to be replaced with SLF4J.

**Comment by dvryaboy** [comment]
a pull request to replace util-logging with SLF4J would be a pretty constructive way to offer criticism

**Comment by fommil** [comment]
@mariusae :+1:

**Comment by devshorts** [comment]
@mariusae since util-logging is being deprecated, is there any suggestion to leverage the logging toggles found in twitter-server to route to slf4j?  Frameworks like finatra are pushing logback+slf4j (which is great) but the integration into the twitter server stack is weird

**Comment by taylorleese** [comment]
@devshorts We're actually working internally on a proposal to move Twitter Server to SLF4J so that's our current tentative plan. @cacoco is working on this so mentioning him here in case he wants to expand on what I've mentioned.

**Comment by cacoco** [comment]
Merged in c458b88161f56768d0226c8419424f8365574b83. Released in https://github.com/twitter/twitter-server/releases/tag/twitter-server-17.10.0.
