### ISSUE TITLE
dalvik support

### ISSUE THREAD

**Issue by mosesn** [twitter/util#126]
We're looking for help to add dalvik support.  This is going to be in a few parts, but basically it's going to be in abstracting away all of the bits that aren't supported by dalvik, in util, finagle, twitter-server.  These are going to be things like jmx, and java.lang.Management.

We don't know yet whether we'll want to merge in these contributions, or make an android-compatible fork, but we're happy to discuss.

**Comment by chester89** [comment]
So it will be possible to run finagle services on Android phone? :+1:

**Comment by mosesn** [comment]
I don't know if you'd be able to host a server easily, but you could certainly use the finagle client.

**Comment by kevinoliver** [comment]
Closing this as there hasn't been any interest. Should anyone get excited about it in the future, we can reopen it.
