### ISSUE TITLE
java 6 support dropped?

### ISSUE THREAD

**Issue by koertkuipers** [twitter/util#127]
this is a question more than an issue... no more java 6 support? 

on develop branch:
[error] /home/koert/src/twitter/util/util-core/src/test/scala/com/twitter/io/BufTest.scala:429: object StandardCharsets is not a member of package java.nio.charset
[error]     import java.nio.charset.StandardCharsets.UTF_8

**Comment by koertkuipers** [comment]
it must just be a mistake. i fixed that one import and had no more issues

**Comment by mosesn** [comment]
@koertkuipers yes, we dropped java 6 support.  We only announced it on the finaglers [listserv][0] (since util doesn't have its own listserv).

[0]: https://groups.google.com/forum/#!searchin/finaglers/java$206/finaglers/3IFfjryHbVo/r9osYwyfI60J
