### ISSUE TITLE
Alternate ShardCoordinator Policies?

### ISSUE THREAD

**Issue by drob** [twitter/util#129]
First off, thank you for an excellent library! This has already saved me from writing some tricky code.

I noticed that `ShardCoordinator` uses a linear scan over the set of possible IDs. Would you be open to a PR to make this configurable with the current behavior as a default? In particular, I was hoping to add an option to shuffle `availableIds` before attempting to acquire the locks.

Thanks again, in any case!

**Comment by mosesn** [comment]
That seems fine, but could you elaborate on why you're interested in this?

**Comment by drob** [comment]
I was thinking about a pathological case in which N workers starting at once would cause a lot of unnecessary node creation attempts, but on second thought this would require very unlucky timing, and the failure mode wouldn't even be that bad assuming N on the order of 1000.
