### ISSUE TITLE
Add broker receiver and broker sender types

### ISSUE THREAD

**Issue by rightfold** [twitter/util#130]
It would be useful to have views of brokers than can only receive or only send, such that a receiver has only `?`, `??`, `recv...` methods and a sender has only `!`, `!!`, `send...` methods. This would be useful in particular in co- and contravariant situations. This is similar to unidirectional channels in Go.

**Comment by rightfold** [comment]
I'll craft a pull request to demonstrate my intent.

**Comment by mosesn** [comment]
Are you still working on a pull request?  Happy to help with it.

**Comment by rightfold** [comment]
I haven't done any Scala programming in a while, but I do have some ideas about the possible implementations:

1. `Broker[T]` could be a subtype of both `BrokerReceiver[T]` and `BrokerSender[T]`.
2. `Broker[T]` is unchanged, and new types `BrokerReceiver[T]` and `BrokerSender[T]` take a `Broker[T]` as a constructor argument.

**Comment by luciferous** [comment]
@rightfold how's this going?

**Comment by mosesn** [comment]
@rightfold looks like there hasn't been an update in over a year, so I figure you're probably too busy to work on this?  I'm going to close this ticket for now, but feel free to reopen if you decide you're interested again.  As before, happy to help if you have any questions!
