### ISSUE TITLE
Future "collect" does not stop if any of the futures fail?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [twitter/util#134]
I'm wondering if there's any existing implementation of "collect" that do not stop if any of the futures fail (compared with https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L352)

The fact is that, we may query various backends asynchronously, but still keep serving even if some of the backends suffer.

**Comment by sprsquish** [comment]
Check out select or collectToTry

**Comment by vkostyukov** [comment]
I believe you can use [Future.collectToTry](https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Future.scala#L416-L417) for that.

Probably, [finaglers](https://groups.google.com/forum/#!forum/finaglers) is a better place to ask that sort of questions so other folks can easily find it.

**Comment by StarWindMoonCloud** [comment]
Thank you for the quick response, question answered, and will try finaglers next time.
