### ISSUE TITLE
Charsets.scala not available in any maven repo?

### ISSUE THREAD

**Issue by bbarker** [twitter/util#136]
Hi All,

Sorry if I'm looking the wrong place; I've had no luck with `import com.twitter.io.Charsets` when importing packages from http://maven.twttr.com/, and indeed the date of the packages and the source jar files I downloaded seem to confirm the expectation. 

It is, however, referenced in the Twitter Server docs:
https://twitter.github.io/twitter-server/

I don't think this is a show stopper by any stretch, but it does seem the util-core packages in maven are somewhat dated.

**Comment by travisbrown** [comment]
Recent versions of util are published to [Maven Central](http://central.maven.org/maven2/com/twitter/util-core_2.10/6.25.0/util-core_2.10-6.25.0.jar), not `maven.twttr.com`.

Only a handful of Twitter's open source JVM libraries (e.g. [Metrics](https://twitter.github.io/twitter-server/Features.html#metrics)) are now being published to `maven.twttr.com`, and it still exists only for a couple of fairly arcane reasons—we're actively trying to kill it.

Sorry about the confusion!

**Comment by bbarker** [comment]
Aha, thanks! Just FYI, I did find one dependency that wasn't available on Maven Central: an old version of libthrift:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':providedCompile'.
> Could not find org.apache.thrift:libthrift:0.5.0.
  Searched in the following locations:
      https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.pom
      https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.jar
      https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.pom
      https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.jar
      file:/C:/Users/brand_000/.m2/repository/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.pom
      file:/C:/Users/brand_000/.m2/repository/org/apache/thrift/libthrift/0.5.0/libthrift-0.5.0.jar
  Required by:
      com.cloudera:CommVis:1.0-SNAPSHOT > com.twitter:twitter-server_2.11:1.11.0 > com.twitter:finagle-zipkin_2.11:6.26.0
      com.cloudera:CommVis:1.0-SNAPSHOT > com.twitter:twitter-server_2.11:1.11.0 > com.twitter:finagle-zipkin_2.11:6.26.0 > com.twitter:finagle-thrift_2.11:6.26.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

It seems to be in `maven.wttr.com`, however:
http://maven.twttr.com/org/apache/thrift/libthrift/0.5.0/

So I'll keep using it for the moment.

**Comment by travisbrown** [comment]
@bbarker Yes, you'll need `maven.twttr.com` in your resolvers for that version of libthrift (as well as Metrics, if you're using that). We're taking steps toward updating libthrift internally, but don't have a definite timeline yet.

**Comment by bbarker** [comment]
Thanks!
