### ISSUE TITLE
Support for Reactive Streams on roadmap?

### ISSUE THREAD

**Issue by schrepfler** [twitter/util#142]
Asking here as AsyncStream is in here. In recent news as reactive streams got finalised many frameworks jumped on board which means they can all share some common traits and interop capabilities. Wouldn't finagle also benefit from this?

**Comment by mosesn** [comment]
@mariusae has been our liaison with the reactive streams work, so he would know better, but I think it sounds pretty reasonable.  Maybe it would make sense to provide a util-reactivestreams module with twitter bijections between AsyncStream and reactive streams?  Do you want to take a stab?

**Comment by luciferous** [comment]
+1 to that. Though beneficial for Finagle, interop with reactive streams may be low priority for us.

**Comment by mosesn** [comment]
This continues to be low priority for us, but we would welcome a PR to improve our interoperability.

**Comment by schrepfler** [comment]
What would a proposed approach be? A set of isomorphisms like the Twitter Future <-> Scala Future or would it be good to have some design principle/generalisation document first? I think Reactive Streams/Rx might open some space in extending/generalising Finagle's Future/Service/Filter paradigm and without a seminal document like https://monkey.org/~marius/funsrv.pdf I think any development would be just a hack to enable interop. In a way, Finagle's ecosystem paved the way to well interconnected systems but it would be a shame if we can't have a principled view how the composition should work and which properties should be upheld when composing (both ways) before just hacking away.

**Comment by luciferous** [comment]
@schrepfler 
> What would a proposed approach be?

I imagine scalaz has something similar to map between Tasks (or some streaming derivative of) and Reactive Streams. Let's start there.

> A set of isomorphisms like the Twitter Future <-> Scala Future or would it be good to have some design principle/generalisation document first?

The semantics should follow "ListT done right", only that our implementation uses a free monad with the monad specialized to Twitter's Future.

**Comment by mosesn** [comment]
@schrepfler do you want to come up with a proposal?

**Comment by schrepfler** [comment]
I don't think I'm best placed. Ideally it would be someone which understands well Twitter's Future but also Reactive Streams.

**Comment by kevinoliver** [comment]
we are doing a bunch of work to improve streaming in Finagle / Finatra. this may include reactive streams converters in Finatra.

however, we don't have plans for this in util.
