### ISSUE TITLE
Caffeine cache (migrate from Guava)

### ISSUE THREAD

**Issue by ben-manes** [twitter/util#147]
`util-cache` currently uses Guava, which is feature rich with modest performance. The Java 8 rewrite, [Caffeine](https://github.com/ben-manes/caffeine), has [higher performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks) and a [better hit rate](https://github.com/ben-manes/caffeine/wiki/Efficiency). It uses an updated API and provides optional Guava adapters to simplify migration. As Guava's cache is in maintenance (neither Charles or I work on it anymore), this is a reasonable upgrade path.

**Comment by mosesn** [comment]
@ben-manes we can't use java 8 features yet, but when we do, maybe it would make sense to provide something like GuavaCache for caffeine?

**Comment by ben-manes** [comment]
Sounds good. You might prefer using `AsyncLoadingCache` with [scala-java8-compat](https://github.com/scala/scala-java8-compat) for handling `Future[V]` values.

btw, I think [evict(key: K, f: Future[V])](https://github.com/twitter/util/blob/develop/util-cache/src/main/scala/com/twitter/cache/guava/GuavaCache.scala#L54) can use `asMap().remove(k, v)`.

**Comment by mosesn** [comment]
good catch!  I wonder why I got that wrong before.  I'll fix it.

**Comment by mosesn** [comment]
We have an experimental version [here][0]!

[0]: https://github.com/twitter/util/commit/e0f47784341fd54324a4e8564818f21453cd7bd2
