### ISSUE TITLE
The project can't build,I hope it can,thanks

### ISSUE THREAD

**Issue by jacksu** [twitter/util#149]

**Comment by jacksu** [comment]
sbt.ResolveException: unresolved dependency: com.twitter.common#io;0.0.67: not found

**Comment by mosesn** [comment]
@jacksu can you check if you can access [maven.twttr.com][0]?  Looks like you live in Xi'an, some people have had problems with GFW China in the past, worth making sure you're not running into that.

[0]: https://maven.twttr.com/com/twitter/common/io/0.0.67/
