### ISSUE TITLE
Update Scaladoc at http://twitter.github.com/util

### ISSUE THREAD

**Issue by alexeyr** [twitter/util#15]
Currently documentation there is for 1.8.6-SNAPSHOT

**Comment by vkostyukov** [comment]
I believe this is no longer actual.

**Comment by travisbrown** [comment]
The 1.8.6-SNAPSHOT docs were the last version before Unidoc, and for the sake of search engines they're still available. I noticed last summer that they were showing up in search results and [added redirects](https://github.com/travisbrown/util/commit/72ee56d929fde621011fc617630a18d18f65d4f0) and canonical links to the new docs, which should allow us to remove the old ones at some point.

Thanks for catching this issue, @vkostyukov—I didn't notice it at the time, and agree that it should be closed.
