### ISSUE TITLE
Until-cache refresh behaviour 

### ISSUE THREAD

**Issue by lukiano** [twitter/util#150]
Looking at refresh.every() method it seems that if a refresh fails, it evicts the promise, so that the next request forces a new call. 
I think that if the refresh fails, its promise should return the old data instead of an exception, besides evicting the entry.

**Comment by kevinoliver** [comment]
Might depend on what the user wants, hard for me to say. I think making this a policy seems reasonable though if you are interested in a PR.

**Comment by mosesn** [comment]
@lukiano I agree that if you have this use case, we should make it a policy.  The argument for the existing implementation is that it tries to maximize correctness over latency.

**Comment by lukiano** [comment]
I found an alternative via wrapping the refresh in an exponential retry. It'd be cool to share the Exponential Retry for Futures located in util-zk as another Future utility in the concurrent package of util-core. Thanks!
