### ISSUE TITLE
twitter Promise does not preserve order of callbacks

### ISSUE THREAD

**Issue by scf37** [twitter/util#157]
Test code:

```    val p = Promise[Int]

    p.onSuccess { _ =>
      println("1")
    }
    p.onSuccess { _ =>
      println("2")
    }
    p.onSuccess { _ =>
      println("3")
    }
    p.onSuccess { _ =>
      println("4")
    }
    p.onSuccess { _ =>
      println("5")
    }

    p.setValue(42)```

Expected: 1 2 3 4 5

Actual: 1 5 4 3 2

**Comment by mosesn** [comment]
@scf37 right–I think the guarantee we provide is that if you have a data dependency (like if you were mapping iteratively over these callbacks) we will preserve order, but we have no such guarantee when you're hanging callbacks off of a single Future.

**Comment by scf37** [comment]
@mosesn Thanks for the explanation. What is the right way to implement something like that but keeping request order:

```
val sf: ServiceFactory[Int, Int] = ....
val serviceFuture = sf(clientConn)

//send request as soon as service arrives
//unfortunately this does not keep request order
def sendRequest(req: Int): Future[Int] = serviceFuture.map(s => s(req))
```

?

**Comment by stuhood** [comment]
@scf37 : @mosesn left an example of how to do this in his response.

If there are no explicit data dependencies and you're doing this purely for sideeffect ordering, then you can use `before`... although it is intended for use with async effects:
```
val p = Promise[Unit]()

def fprintln(str: String): Future[Unit] = { println(str); Future.Unit }

p.before {
  fprintln("1")
}.before {
  fprintln("2")
}.before {
  fprintln("3")
}.before {
  fprintln("4")
}.before {
  fprintln("5")
}

p.setValue(Unit)
```
