### ISSUE TITLE
util-zk: monitorTree not working

### ISSUE THREAD

**Issue by thefourtheye** [twitter/util#158]
I am using util-zk with Akka. When I receive a particular message I start watching a node, with this

``` scala
ZNode(client, path).monitorTree().foreach((u: TreeUpdate) => {
  Console.err.println(u.added, u.removed, u.parent)
  ...
})
```

To check if it is working, I added another child to that particular node immediately after start monitoring. But this function never gets called. I used both curator test's TestingServer also a real ZooKeeper server. What am I doing wrong?

I am using Ubuntu 14.04 in a Virtual Machine, util-zk v6.33.0, Scala v2.11.8, Akka v2.4.2.

**Comment by mosesn** [comment]
@thefourtheye sorry for the delay in getting back to you!  this looks right to me, can you reproduce it using our [test system][0]?

[0]: https://github.com/twitter/util/blob/develop/util-zk/src/test/scala/com/twitter/zk/ZkClientTest.scala#L697

**Comment by luciferous** [comment]
This is a very old issue and util-zk is being considered from removal.
