### ISSUE TITLE
2.12-ification

### ISSUE THREAD

**Issue by mosesn** [twitter/util#162]
In order to support 2.12, we need to add crossScalaVersions to Build.scala, and make sure everything compiles.  Not every scala library will be built against the current snapshot, so we may have to support different versions from 2.11 to 2.12.  If part of an API has churned (scalacheck in particular is susceptible to this) we may need to upgrade the 2.11 library version to make progress.  If that happens, contact me (@mosesn) and I'll navigate the upgrade for you–it's a little complicated because we will need to upgrade all of our internal libraries, not just finagle.

I expect most of the modules to be straightforward to upgrade.  The one that might not be is `util-eval`, which we still can't get rid of because `ostrich` depends on it.  I'll see if I can remove it from `ostrich`, but I'm not holding my breath.

- [x] util-app @jeffreyolchovy https://github.com/twitter/util/pull/163
- [x] util-benchmark @jeffreyolchovy 
- [x] util-cache @jeffreyolchovy 
- [x] util-class-preloader @jeffreyolchovy 
- [x] util-codec @jeffreyolchovy 
- [x] util-collection @jeffreyolchovy 
- [x] util-core @jeffreyolchovy 
- [x] util-eval @jeffreyolchovy 
- [x] util-events @jeffreyolchovy 
- [x] util-function @jeffreyolchovy 
- [x] util-hashing @jeffreyolchovy 
- [x] util-jvm @jeffreyolchovy 
- [x] util-lint @jeffreyolchovy 
- [x] util-logging @jeffreyolchovy 
- [x] util-reflect @jeffreyolchovy 
- [x] util-registry @jeffreyolchovy 
- [x] util-stats @jeffreyolchovy 
- [x] util-test @jeffreyolchovy 
- [x] util-thrift @jeffreyolchovy 
- [x] util-zk @jeffreyolchovy 
- [x] util-zk-common @jeffreyolchovy 
- [x] util-zk-test @jeffreyolchovy 

If you want to claim a module, please let us know in this thread!  I'll annotate different modules once they're done.

Probably a good way to start is for someone to try add 2.12 support for all of them, and then report back which ones still fail, so we know which ones are tricky and which ones work trivially.

**Comment by jeffreyolchovy** [comment]
I'll give this one a shot. Will report back with initial results.

**Comment by jeffreyolchovy** [comment]
From a very high level, we're missing 2.12 artifacts for:
- `org.scalacheck#scalacheck`
- `org.scoverage#sbt-scoverage`

And the following dependencies have to be updated to retrieve a 2.12 artifact:
- `org.scalatest#scalatest` (2.2.4 to 2.2.6)

`sbt-scoverage` is an interesting case, as the offending `libraryDependencies` are injected via the plugin, which effects all modules. The sbt plugin itself, obviously, need only be built against 2.10, however, it requires that `org.scoverage#scalac-scoverage-runtime` and `org.scoverage#scalac-scoverage-plugin` have 2.12 artifacts. These do not yet exist.

The lack of a `scalacheck` 2.12 artifact effects `util-collection`, `util-core`, `util-hashing`, and `util-stats`.

**Comment by mosesn** [comment]
@jeffreyolchovy can we try using a different library version depending on the scala version?  and can we only enable scoverage for 2.11?

**Comment by jeffreyolchovy** [comment]
@mosesn, yes I was able to do the former. I added the following to the `sharedSettings`:
```
libraryDependencies := {
  libraryDependencies.value.map {
    case moduleId: ModuleID
      if moduleId.organization == "org.scoverage"
      && scalaVersion.value.startsWith("2.12") =>
      moduleId.copy(name = moduleId.name.replace(scalaVersion.value, "2.11"))
    case moduleId =>
      moduleId
  }   
}  
```
That is pretty hacky, so I imagine there is a better way. I attempted to use the `cross` operator on `ModuleID`, but that only seems useful for dependencies that were specified without the `%%` upon declaration. Again, we don't have control over the declaration site of the dependencies since that happens in the plugin.

I don't think your latter suggestion is a feasible option (without further changes) because `ScoverageKeys` are used in Build.scala and conditionally disabling the plugin would then cause compilation problems of the project itself.

So, there is at least *something* that works, and it can potentially be cleaned up. Will keep hacking.

**Comment by stuhood** [comment]
@jeffreyolchovy : Thanks for the patch!

The inference failure for `Witness` seems fairly fundamental... from what I can tell, the compiler is failing/refusing to infer `Any`, so the following edit works as well:
```
diff --git a/util/util-core/src/main/scala/com/twitter/util/Event.scala b/util/util-core/src/main/scala/com/twitter/util/Event.scala
index 7f49864..d06b1cd 100644
--- a/util/util-core/src/main/scala/com/twitter/util/Event.scala
+++ b/util/util-core/src/main/scala/com/twitter/util/Event.scala
@@ -476,7 +476,7 @@ object Witness {
   /**
    * A [[Witness]] which prints to the console.
    */
-  val printer: Witness[Any] = Witness(println(_))
+  val printer: Witness[Any] = Witness(println(_: Any))
 }

 /**
```

I wonder if this scalac-bug-worthy. Simple repro looks like:
```
object B {
  def apply[T](f: T=>Unit): T=>Unit = f
}

val x = B(println(_))
```
```
[error] B.scala:18: missing parameter type for expanded function ((x$1: <error>) => println(x$1))
[error]   val x = B(println(_))
[error]                     ^
[warn] B.scala:18: a type was inferred to be `Any`; this may indicate a programming error.
[warn]   val x = B(println(_))
[warn]                    ^
```

**Comment by jeffreyolchovy** [comment]
@stuhood, i like that, and it keeps it nice and concise too.

I'm not exactly sure if this is a scalac bug vs. an advertised-yet-difficult-for-me-to-understand change (http://scala-lang.org/news/2.12.0-M4/#sam-types -- click through to underlying issue #4971 for more info).

That's a bit over my head, but, as an aside, if `Witness.apply` wasn't overloaded, something as simple as `Witness(println)` would work as well. Which explains why declarations like: `Witness.fromFunction(println)` work.

Compare:
```
Welcome to Scala 2.12.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65).
Type in expressions for evaluation. Or try :help.

scala> object B {
     |   def apply[T](f: T=>Unit): T=>Unit = f
     | }
defined object B

scala> 

scala> val x = B(println(_))
<console>:12: error: missing parameter type for expanded function ((x$1: <error>) => println(x$1))
       val x = B(println(_))
                         ^

scala> val x = B(println)
x: Any => Unit = $$Lambda$1231/2043519108@4bcc23f8

scala> val x = B(println(_: Any))
x: Any => Unit = $$Lambda$1232/2044509673@6b33db97
```
vs.

```
trait Foo[A] {
  def foo(a: A): Unit
}

object Foo {
  def apply[A](f: A => Unit): Foo[A] = new Foo[A] { def foo(a: A): Unit = f(a) }
  def apply[A](ref: java.util.concurrent.atomic.AtomicReference[A]): Foo[A] = new Foo[A] { def foo(a: A): Unit = ref.set(a) }
}


// Exiting paste mode, now interpreting.

defined trait Foo
defined object Foo

scala> Foo(println)
<console>:16: error: overloaded method value apply with alternatives:
  [A](ref: java.util.concurrent.atomic.AtomicReference[A])Foo[A] <and>
  [A](f: A => Unit)Foo[A]
 cannot be applied to (Unit)
       Foo(println)
       ^

scala> Foo(println(_))
<console>:16: error: missing parameter type for expanded function ((x$1: <error>) => println(x$1))
       Foo(println(_))
                   ^

scala> Foo(println(_: Any))
res2: Foo[Any] = Foo$$anon$1@1c1b9e66
```

**Comment by mosesn** [comment]
Ignoring the overloading case, I'm also not that familiar with what's going on here, but it smells to me like it's a bug that SAMs can be converted to functions correctly now, but placeholder syntax requires specifying the argument.  It smells like a regression in placeholder syntax to me.

For the overloading case you've described, this smells like a bug to me too.  Unlike `Comparator` in the sam-types announcement example, which is [annotated][0] a `FunctionalInterface`, `AtomicReference` is not a function under the hood, and the compiler should be able to disambiguate the overload.

[0]: https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html

**Comment by idarlington** [comment]
Hi, I am interested where can I start?

**Comment by mosesn** [comment]
@jeffreyolchovy has started a branch, which you can take a look at at #163.  He hasn't mentioned `util-collection` as having problems, but if you're curious, you can check out his branch and try building it yourself.

I'm a little suspicious that `util-eval` will have problems, so it would be worth trying it out too.  Thanks @idarlington!

**Comment by idarlington** [comment]
Ok thanks @mosesn , excited to be a part of this, hopefully my first PR.

**Comment by jeffreyolchovy** [comment]
@idarlington please also see the corresponding PR https://github.com/twitter/util/pull/163 for more info.

**Comment by jeffreyolchovy** [comment]
@mosesn @idarlington here is the output of `+test` for both `util-collection` and `util-eval`. All tests for both modules pass but maybe you'll find something else here that is suspicious regardless of the successful output:

`util-collection`
```
> project util-collection
[info] Set current project to util-collection (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
> +test
[info] Setting version to 2.11.8
[info] Reapplying settings...
[info] Set current project to util-collection (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
[info] Updating {file:/Users/jeffo/Projects/jvm/twitter/util/}util-collection...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 5 Scala sources to /Users/jeffo/Projects/jvm/twitter/util/util-collection/target/scala-2.11/classes...
[info] [info] Cleaning datadir [/Users/jeffo/Projects/jvm/twitter/util/util-collection/target/scala-2.11/scoverage-data]
[info] [info] Beginning coverage instrumentation
[info] [info] Instrumentation completed [261 statements]
[info] [info] Wrote instrumentation file [/Users/jeffo/Projects/jvm/twitter/util/util-collection/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] [info] Will write measurement data to [/Users/jeffo/Projects/jvm/twitter/util/util-collection/target/scala-2.11/scoverage-data]
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 6 Scala sources to /Users/jeffo/Projects/jvm/twitter/util/util-collection/target/scala-2.11/test-classes...
[info] LRUMapTest:
[info] - LRUMap creation
[info] - LRUMap insertion
[info] - LRUMap eviction
[info] GenerationalQueueTest:
[info] - ExactGenerationalQueue: Don't collect fresh data
[info] - ExactGenerationalQueue: Don't collect old data recently refreshed
[info] - ExactGenerationalQueue: collect one old data
[info] - ExactGenerationalQueue: collectAll old data
[info] - ExactGenerationalQueue: generate a long chain of bucket (if applicable)
[info] - ExactGenerationalQueue: Don't collect old data
[info] - BucketGenerationalQueue: Don't collect fresh data
[info] - BucketGenerationalQueue: Don't collect old data recently refreshed
[info] - BucketGenerationalQueue: collect one old data
[info] - BucketGenerationalQueue: collectAll old data
[info] - BucketGenerationalQueue: generate a long chain of bucket (if applicable)
[info] - BucketGenerationalQueue: Don't collect old data
[info] - BucketGenerationalQueue check removals
[info] SetMakerTest:
[info] - SetMaker
[info] ImmutableLRUTest:
[info] - ImmutableLRU insertion
[info] - ImmutableLRU eviction
[info] - ImmutableLRU removal
[info] RecordSchemaTest:
[info] - apply should throw IllegalStateException when field is uninitialized
[info] - apply should compute, store and return default when field is initialized with default
[info] - apply should return field value when field is explicitly initialized
[info] - lock should throw IllegalStateException when field is uninitialized
[info] - lock should compute and store default when field is initialized with default
[info] - update should reassign when field is not locked
[info] - update should throw IllegalStateException when field is locked
[info] - updateAndLock should update and lock
[info] - copy should copy
[info] - copy should not be modified when the original is updated
[info] - locked state should be copied
[info] - copy should be able to overwrite a locked field
[info] ScalaTest
[info] Run completed in 794 milliseconds.
[info] Total number of tests run: 32
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 32, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 32, Failed 0, Errors 0, Passed 32
[success] Total time: 7 s, completed May 28, 2016 8:10:59 PM
[info] Setting version to 2.12.0-M4
[info] Reapplying settings...
[info] Set current project to util-collection (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
[info] LRUMapTest:
[info] - LRUMap creation
[info] - LRUMap insertion
[info] - LRUMap eviction
[info] GenerationalQueueTest:
[info] - ExactGenerationalQueue: Don't collect fresh data
[info] - ExactGenerationalQueue: Don't collect old data recently refreshed
[info] - ExactGenerationalQueue: collect one old data
[info] - ExactGenerationalQueue: collectAll old data
[info] - ExactGenerationalQueue: generate a long chain of bucket (if applicable)
[info] - ExactGenerationalQueue: Don't collect old data
[info] - BucketGenerationalQueue: Don't collect fresh data
[info] - BucketGenerationalQueue: Don't collect old data recently refreshed
[info] - BucketGenerationalQueue: collect one old data
[info] - BucketGenerationalQueue: collectAll old data
[info] - BucketGenerationalQueue: generate a long chain of bucket (if applicable)
[info] - BucketGenerationalQueue: Don't collect old data
[info] - BucketGenerationalQueue check removals
[info] SetMakerTest:
[info] - SetMaker
[info] ImmutableLRUTest:
[info] - ImmutableLRU insertion
[info] - ImmutableLRU eviction
[info] - ImmutableLRU removal
[info] RecordSchemaTest:
[info] - apply should throw IllegalStateException when field is uninitialized
[info] - apply should compute, store and return default when field is initialized with default
[info] - apply should return field value when field is explicitly initialized
[info] - lock should throw IllegalStateException when field is uninitialized
[info] - lock should compute and store default when field is initialized with default
[info] - update should reassign when field is not locked
[info] - update should throw IllegalStateException when field is locked
[info] - updateAndLock should update and lock
[info] - copy should copy
[info] - copy should not be modified when the original is updated
[info] - locked state should be copied
[info] - copy should be able to overwrite a locked field
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 666 milliseconds.
[info] Total number of tests run: 32
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 32, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 32, Failed 0, Errors 0, Passed 32
[success] Total time: 1 s, completed May 28, 2016 8:11:03 PM
```

`util-eval`
```
> project util-eval
[info] Set current project to util-eval (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
> +test
[info] Setting version to 2.11.8
[info] Reapplying settings...
[info] Set current project to util-eval (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
[info] EvalTest:
[info] Evaluator
[info] - should apply('expression')
[info] - should apply(new File(...))
[info] - should apply(new File(...), new File(...))
[info] - should apply(new File(...) with a dash in the name with target
[info] - should apply(new File(...) with target
[info] - should apply(InputStream)
[info] - should uses deprecated
[info] - should inPlace('expression')
[info] - should check
[info] - should #include
[info] - should recursive #include
[info] - should toSource returns post-processed code
[info] - should throws a compilation error when Ruby is #included
[info] - should clean class names
[info]   should allow custom error reporting
[info]   - when not report errors on success
[info]   - when report errors on bad code
[info]   - when reset reporter between invocations
[info] Run completed in 3 seconds, 249 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 5 s, completed May 28, 2016 8:14:39 PM
[info] Setting version to 2.12.0-M4
[info] Reapplying settings...
[info] Set current project to util-eval (in build file:/Users/jeffo/Projects/jvm/twitter/util/)
[info] EvalTest:
[info] Evaluator
[info] - should apply('expression')
[info] - should apply(new File(...))
[info] - should apply(new File(...), new File(...))
[info] - should apply(new File(...) with a dash in the name with target
[info] - should apply(new File(...) with target
[info] - should apply(InputStream)
[info] - should uses deprecated
[info] - should inPlace('expression')
[info] - should check
[info] - should #include
[info] - should recursive #include
[info] - should toSource returns post-processed code
[info] - should throws a compilation error when Ruby is #included
[info] - should clean class names
[info]   should allow custom error reporting
[info]   - when not report errors on success
[info]   - when report errors on bad code
[info]   - when reset reporter between invocations
[info] Run completed in 3 seconds, 38 milliseconds.
[info] Total number of tests run: 17
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 17, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 3 s, completed May 28, 2016 8:14:45 PM
```

**Comment by mosesn** [comment]
LGTM

**Comment by idarlington** [comment]
Hi @jeffreyolchovy , Checked out your branch and it compiles successfully.

**Comment by mosesn** [comment]
@stuhood @jeffreyolchovy I filed https://issues.scala-lang.org/browse/SI-9796 to see if the scala folks can help figure out the type inference regression we found in Witness.  I think it somehow has to do with traits which have only one method–I think they might be compiled down to java functions under the hood.

**Comment by mosesn** [comment]
@idarlington it looks like this issue is going to be easier than we thought it would be.  If you're still interested in getting involved in util, you can tackle https://github.com/twitter/util/issues/107, or if you're interested in helping with the finagle 2.12-support effort in general, ostrich and scrooge are the two next steps for getting 2.12 going!

**Comment by jeffreyolchovy** [comment]
@idarlington you want to take ostrich, and i'll continue with scrooge?

**Comment by mosesn** [comment]
@stuhood @jeffreyolchovy turned out I didn't understand what a SAM was.  Updatable is a SAM, which is why there's an inference problem.

**Comment by idarlington** [comment]
Hi, sorry i don't get that @jeffreyolchovy what's wrong?  i thought it compiled successfully.

**Comment by jeffreyolchovy** [comment]
@idarlington, nothing wrong, just seeing if you had interest in taking https://github.com/twitter/ostrich/issues/74. Very similar to this issue, just a different project (and it has `util` as a dependency).

**Comment by idarlington** [comment]
ok cool, got it. I would take ostrich. Thanks @jeffreyolchovy

**Comment by spockz** [comment]
Any ideas on when a 2.12 version of twitter-util will be released?

**Comment by mosesn** [comment]
@spockz we're blocked on migrating to scalatest 3.x since they stopped publishing scalatest 2.x for 2.12.x.  We'll start publishing for 2.12.0 once we've switched.  My guess (not a promise) is that we'll first publish for 2.12.0 in early December.

**Comment by spockz** [comment]
@mosesn thanks for the update!
