### ISSUE TITLE
There is a cache to my http request?

### ISSUE THREAD

**Issue by tacnoman** [twitter/util#165]
Hello guys.

I want to make a cache in my http request (rest response).

There is an lib here to make this?

**Comment by mosesn** [comment]
@tacnoman hi!  Welcome to util.  We have a library for making asynchronous caches, `util-cache`, which is documented [here][0].  Could you elaborate on the problem you're trying to solve?  `util-cache` works well with finagle, but if you're using a synchronous http client, it might not be the best fit.

[0]: https://github.com/twitter/util/tree/develop/util-cache

**Comment by tacnoman** [comment]
Thanks! xD
