### ISSUE TITLE
Java 7 support needed

### ISSUE THREAD

**Issue by nilday** [twitter/util#171]
I strongly suggest that the Twitter Util continuously support java 7, I don’t see a strong motivation of give up the support. On the other hand, there ’s so many companies which still use java 7 in production environment ,which is what I meet with, that I have to merge some bug fix and new feature to old release manually.

**Comment by mosesn** [comment]
@nilday I'm sorry to hear that.  We've already made the decision to drop support for Java 7.  Java 7 reached its end of life over a year ago, and at some point we need to continue moving forward.  I know we're not the only library that has dropped support for Java 7, so it might be worth lobbying your company to start working on the Java 8 migration.
