### ISSUE TITLE
fragile tests intermittently fail in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#173]
at https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/ you'll see a run of red failed test runs 216–220. sometimes com.twitter.util.FuturePoolTest fails, sometimes it's com.twitter.finagle.stats.CumulativeGaugeTest

I haven't looked at the tests in question — perhaps they just need longer timeouts?

**Comment by mosesn** [comment]
@SethTisue can you set `SKIP_FLAKY`?  We use that when we don't think the tests will be reliable in a [ci environment][0], like tests that check what happens after we trigger a garbage collection.  Not sure what's going on with FuturePoolTest though, we haven't seen that before.

How did you start running into this?  Did you just start running tests for util?

[0]: https://github.com/twitter/util/blob/develop/util-stats/src/test/scala/com/twitter/finagle/stats/CumulativeGaugeTest.scala#L47

**Comment by SethTisue** [comment]
nothing has changed at our end recently, except perhaps heavier server load. I will set `SKIP_FLAKY`

**Comment by mosesn** [comment]
@SethTisue we dug into the FuturePoolTest and figured out the problem, should be open sourced Monday.  is the CumulativeGaugeTest better now?

**Comment by SethTisue** [comment]
> @SethTisue we dug into the FuturePoolTest and figured out the problem, should be open sourced Monda

awesome

> is the CumulativeGaugeTest better now?

I believe we're now successfully skipping it with `SKIP_FLAKY`

**Comment by kevinoliver** [comment]
Ok the `FuturePoolTest` fix went in with https://github.com/twitter/util/commit/4a939764c58784aeddc14878cb287ba1343bfa1d so we should be good here. Thanks @SethTisue.
