### ISSUE TITLE
AppTest consistently failing in Scala (2.11, JDK8) community build

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#180]
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk8-integrate-community-build/ shows jobs 248, 249, 250, 251 all failing in AppTest

there are too many projects in the community build for me to investigate most individual failures, but the error logs are all there at the link

maybe it's spurious somehow... or.... we have merged some PRs for Scala 2.11.9 recently, so it's not impossible there is some resulting regression here in this repo. you can test with a recent 2.11.x nightly with e.g.:

```
resolvers += "Scala nightlies" at "https://scala-ci.typesafe.com/artifactory/scala-release-temp/"
scalaBinaryVersion := "2.11"
scalaVersion := "2.11.9-f66ed4d-nightly"
```

I was able to reproduce the failure locally this way.

**Comment by SethTisue** [comment]
for now, to make the community build green again I will disable compiling and running of tests in your util-app subproject

**Comment by SethTisue** [comment]
util-logging is affected as well:

```
[twitter-util] [error] Failed tests:
[twitter-util] [error] 	com.twitter.logging.AppTest
```

**Comment by bryce-anderson** [comment]
Hi @SethTisue. This seems to be building/testing fine with the nightly version you've provided on my end. I think this was fixed recently by this commit: https://github.com/twitter/util/commit/3bbf6c936b04fe8b8f930137cf929c38b6618aa5. I can't tell for sure, but it looks like you're using the source for twitter-util 6.38 which didn't include that patch.
Do you need anything from our end?

**Comment by SethTisue** [comment]
ah, we were using the `develop` branch in our 2.12 community build, but our 2.11.x-jdk8 build was using your `master` branch, which doesn't have the fix yet

using `develop` in the 2.12 one has been smooth sailing in recent months, so I'll provisionally change the 2.11.x-jdk8 one to use it as well

thanks!
