### ISSUE TITLE
JsonTunableMapperTest failing

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#185]
seen in Scala 2.12 community build (at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1288/consoleFull), but also reproducible locally just by checking out the `develop` branch and doing `++2.12.1` and `testOnly *JsonTunableMapperTest*`

```
[info] - loadJsonTunables throws an Illegal argument exception when multiple configs found *** FAILED ***
[info]   Expected exception java.lang.IllegalArgumentException to be thrown, but no exception was thrown (JsonTunableMapperTest.scala:221)
```

**Comment by jcrossley** [comment]
Hi Seth! We're in  the process of fixing this, thanks! Note that this should only be an issue on the develop, not release branch.

**Comment by jcrossley** [comment]
All fixed: https://github.com/twitter/util/tree/develop

**Comment by SethTisue** [comment]
green again at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1291/ 👍
