### ISSUE TITLE
TunableMap not usable outside of twitter organization

### ISSUE THREAD

**Issue by nmurthy** [twitter/util#193]
Using `StandardTunableMap` in projects in a namespace outside of `com.twitter` isn't possible (I think).

I'm trying to use tunable parameters in a project which inherits from `TwitterServer`, but as my namespace is `com.zenreach`, I'm not able to access any of the parameters (via `TunableMap.Key[T]` or instantiate a `StandardTunableMap`. I believe it's because the classes are marked as `protected[twitter]`.

My intended usage:
```scala
package com.myorg

object MyJob {
  val clientId = "myjob"
  val tunables = StandardTunableMap(clientId)
  val lightStoreTunable: Tunable[TrafficStore] =
  tunables(TunableMap.Key[TrafficStore]("lightStore"))
  val darkStoreTunable: Tunable[TrafficStore] =
  tunables(TunableMap.Key[TrafficStore]("darkStore"))
  val store = lightStoreTunable.flatMap { lightStore => 
    darkStoreTunable.map { darkStore => 
      DarkReadsStore(lightStore, darkStore)
    }
  }
}
```

**Comment by jcrossley** [comment]
Hi @nmurthy, Tunables are in the experimental phase right now, but we'll definitely be making the API public in the future! That said, I'm not sure that Tunables are what you're looking for here; are you wanting to change backend stores at runtime? Could you clarify what you're trying to do? Tunables don't have a flatMap function.

**Comment by nmurthy** [comment]
Err well yeah I messed up that example. I'm basically trying to be able to hot reload stores at runtime via the Twitter-Server admin endpoints. I'm assuming that if I have a no arg constructor for the types in question, it can probably work?

And I meant to map/flatMap the result of the Tunable[Store], assuming it was Option-Iikeb

**Comment by mosesn** [comment]
@nmurthy hmm, I don't think Tunable is exactly what you want.  I think you're probably better off just adding a new admin endpoint instead of trying to reuse the Tunable admin endpoint, which is really for adjusting configuration values.  Do you think that would solve your problem?

**Comment by nmurthy** [comment]
@mosesn I think you're right. I'm going to go that route. Out of curiosity though, what's an example of a typical usage scenario of a Tunable if not to be able to dynamically change configuration values?

Either way though, I do think that it would be a useful change to make Tunable and TunableMap.Key not `protected [twitter]` if you intend them to be used directly in the future.

**Comment by mosesn** [comment]
@nmurthy we might have a different idea of what "changing a configuration value" means.  We mean something like, "let's adjust this timeout from 100 milliseconds to 200 milliseconds", instead of "trigger some application logic to do something different".  So we're passing a number to a timeout that's different, but not making anything too thrilling happen in the program.

It sounds like you've solved your problem, so I'm going to close this ticket.  Thanks!
