### ISSUE TITLE
CPU Profile not parseable by pprof

### ISSUE THREAD

**Issue by robfig** [twitter/util#211]
Latest pprof can not parse the output of the com.twitter.jvm.CpuProfile class, most likely because CpuProfile produces a legacy profile that became unsupported when pprof was reimplemented in Go.

# Actual Behavior 

With pprof from "go get -u github.com/google/pprof" at a74ae6fb3cd7047c79272e3ea0814b08154a2d3c and running on Mac OS El Capitan, I produced a profile from my server that looks like that following:

```
--- symbol
binary=com.yext.profileservice.ProfileServer
0x0000000000000001 com.yext.rpc.RpcServer$Worker.run(RpcServer.java:356)
0x0000000000000002 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
0x0000000000000003 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
...
---
--- profile
^@^@^@^@^@^@^@^@^C^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^F^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^B^@^@^@^@
...
```
Full file here: https://github.com/robfig/testprofile/blob/master/legacy_profile

Trying to feed that to pprof is unsuccessful

```
$ pprof profile
legacy_profile: parsing profile: unrecognized profile format
pprof: failed to fetch any source profiles
```

### Expected behavior

I expected pprof to accept the profile.

I believe you can reproduce using any profile produced by this class with latest pprof.

Any advice would be much appreciated. I'm afraid that fixing this requires updating to use the protobuf profile format though.

Thanks very much,
Rob

**Comment by kevinoliver** [comment]
Ooof. I don't think we'd want to take a dependency on protobuf for this functionality. Perhaps that dependency could be added in a separate module that you'd have to opt into.

I'm open to other ideas on getting this addressed.

We haven't probably haven't noticed this because internally at Twitter we've been using a combination of `perf` and [Async Profiler](https://github.com/jvm-profiling-tools/async-profiler).

**Comment by robfig** [comment]
Interesting, I haven't seen that before. Thanks for the link. The pprof model seems very attractive to me because our engineers don't have ssh access to production which seems to be required for all the usual Java profiling tools; having the profiles exported over HTTP makes that easy. 

In terms of taking a dependency: copy-and-pasting the .proto file or even the generated code would probably be fine and not result in any difficulty for consumer of your repo (Bazel ships with a basic proto-compiling rule). I understand that this may not be a priority for you though, was just hoping to get a Java profiler without a major implementation.

**Comment by kevinoliver** [comment]
Using the generated code seems like it's worth a look. Depends on what it's dependencies look like.

As for using those tools — you don't need to have ssh access. You can add a TwitterServer admin page (just like [/admin/pprof/profile](https://twitter.github.io/twitter-server/Admin.html#admin-pprof-profile) that does the work for you. For example, our perf page does this and generates the flamegraph for you.

**Comment by robfig** [comment]
Oh, you are correct, you would need a runtime dependency on protobuf. 

That's a good point, although seems more work intensive. pprof comes with a local web server that provides source listing annotated with cpu samples/heap allocations, SVG, and flame graphs. I guess we'd need a Java implementation of each of those views for parity, based on the data from async profiler. At least something basic could be made pretty quickly. 

I'll investigate that avenue, thanks.

**Comment by mariusae** [comment]
> Ooof. I don't think we'd want to take a dependency on protobuf for this functionality. Perhaps that dependency could be added in a separate module that you'd have to opt into

fwiw, they didn't want this dependency in Go, either, and just wrote manual code to encode the profiles. it's not too bad.

**Comment by robfig** [comment]
Ref: https://go.googlesource.com/go/+/master/src/runtime/pprof/proto.go
