### ISSUE TITLE
Dependency on slf4j-simple causes version conflicts

### ISSUE THREAD

**Issue by adleong** [twitter/util#229]
`util-slf4j-api` depends on `slf4j-simple` which brings a logging implementation in to any project which depends on `util-slf4j-api`.  This can cause version conflicts if the project already depends on another version of an `slf4j` implementation.  For example, `finagle-serversets` depends on `slf4j-log4j12:1.7.5`.

`util-slf4j-api` should not depend on any logging implementation (except in test scopes).

**Comment by ryanoneill** [comment]
Hey @adleong, we're looking into getting this fixed up as soon as we can.

**Comment by ryanoneill** [comment]
fyi. https://github.com/twitter/util/commit/3d6d7457d34055a9e9c86ffd112cc477fd557e0f

I'm going to attempt a patch release now.

**Comment by ryanoneill** [comment]
@adleong I've released version 18.9.1 which should be propagating out now and should fix this issue. Let me know how it works out. Thanks.

**Comment by ryanoneill** [comment]
Alex, we've officially released 18.9.1 to address this issue. I'm going to close this one, but please open another one if there are still problems. Thanks!

https://finagle.github.io/blog/2018/09/27/point-release-notes/

**Comment by adleong** [comment]
I'm trying 18.9.1 right now.  I'm able to build a fat JAR without any conflicts and everything looks good so far.  Thanks!
