### ISSUE TITLE
Illegal Reflective Access in Hotspot.scala

### ISSUE THREAD

**Issue by ryanb93** [twitter/util#235]
The following warning is produced when run in a JRE > 9.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.twitter.jvm.Hotspot (file:/hcom/servers/pros/pros.jar) to field sun.management.ManagementFactoryHelper.jvm
WARNING: Please consider reporting this to the maintainers of com.twitter.jvm.Hotspot
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

https://github.com/twitter/util/blob/6f587b35acb19b9e526ff6f0111f9512d091175a/util-jvm/src/main/scala/com/twitter/jvm/Hotspot.scala#L38

**Comment by kevinoliver** [comment]
Thanks. I believe we don't officially support JDK 9+ yet. I think our next version will be JDK 11 which is an LTS release. We have not begun this effort.

**Comment by luciferous** [comment]
We'll be forced to tackle this issue when we target JDK 11.

**Comment by hartmut27** [comment]
side note: as a **work-around** - to suppress the warnings in the log, comatible with OpenJDK 14 JVM: [Gist](https://gist.github.com/hartmut27/915a732f5e09ca4b3e0b9d577572cc76)
