### ISSUE TITLE
Link to your docs 404s

### ISSUE THREAD

**Issue by Bachmann1234** [twitter/util#237]
The api docs linked here https://twitter.github.io/util/ no longer work. 

Seems https://twitter.github.io/util/docs/#com.twitter.util.package does not exist

**Comment by kevinoliver** [comment]
Thanks @Bachmann1234 and apologies for the delay. Looks like this got addressed in the linked commit and then the 18.2 release.

**Comment by Bachmann1234** [comment]
Awesome thanks!
