### ISSUE TITLE
Minor follow-ups from PR #242

### ISSUE THREAD

**Issue by kevinoliver** [twitter/util#245]
Merging PR #242 fixed a broken window. Thanks! 

While merging this internally a few comments were brought up by folks. These were not blockers. Think of them as worth more discussion.

Roughly:
* In `get`, maybe call `Class.forName(className)` once and pass it in to `tryModuleField` and `tryMethod` to reduce overhead?
* In `getAll`, why do we parse `cls` from `info.className`, then do `get(info.className)` vs `get(cls)`? maybe worth reworking `get()` to take `Class`?
* In the test "GlobalFlag.getAll", could we change this to verify the existence of each of the global flags in the `MockClassLoader`?
* In the tests, can we add tests to verify that it doesn't load classes that aren't global flags? it is only checking the happy path today.

**Comment by monkeyroar** [comment]
I'll look into it, can you assign this issue to me?

**Comment by kevinoliver** [comment]
> I'll look into it, can you assign this issue to me?

awesome, thanks!

i must not know the github magic. you don't show up when i try to assign it to you. weird!

**Comment by luciferous** [comment]
@monkeyroar all yours

**Comment by Anurag870** [comment]
Created a PR for this.

**Comment by yufangong** [comment]
This is fixed by https://github.com/twitter/util/pull/250, closing this. Thanks all.
