### ISSUE TITLE
publish for Scala 2.13?

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#253]
as per https://github.com/twitter/util/issues/219, 2.13 publishing is now "enabled", but I don't see any artifacts on Maven Central. opening this new ticket to track status on that

**Comment by yufangong** [comment]
Ugh, I see what's going on here. The cross-building work missed the August release, It should show up after Sep release, which should be in early September.

**Comment by ayoub-benali** [comment]
So there is no way to trigger a `Util 19.8.1` release ?

**Comment by SethTisue** [comment]
it's not so much delay on twitter-util itself here that worries me a bit, it's the prospect of an additional month of delay being inserted at each level of the various dependency chains that start at twitter-util, but then pass through multiple levels of Twitter-published dependencies, eventually reaching Finagle, Spark, and so forth

**Comment by kevinoliver** [comment]
@SethTisue makes sense. @yufangong kicked off the dot release yesterday and should be sorted soon. thanks for your patience.

**Comment by yufangong** [comment]
Hey @SethTisue @ayoub-benali and @martijnhoekstra, util 19.8.1 showed up in Maven Central now.
