### ISSUE TITLE
(FR) language chooser option for twitter GUI / tweetdeck

### ISSUE THREAD

**Issue by drandreaskrueger** [twitter/util#259]
perhaps this repo twitter/util would have been a better place to ask this question?

**DETAILS SEE HERE:** https://github.com/twitter/twitter-text/issues/291

# your questions:

### problem in one sentence:

my followers/following use English PLUS another language. I want to select "English only".

### Expected behavior

A button on each homepage "show only English tweets"

### Actual behavior

button does not exist, tried a myriad of tools, to no avail.

### Steps to reproduce the behavior

Interview someone who is not an English native speaker. Let them tell you their experience.

# Details:

**DETAILS SEE HERE:** https://github.com/twitter/twitter-text/issues/291

**Comment by mosesn** [comment]
@drandreaskrueger please direct feedback about your Twitter experience to Twitter support, this repo is only about the twitter util project specifically.

**Comment by drandreaskrueger** [comment]
Which repo can I use for that?

It makes sense to start a github issue, where coders can communicate & cooperate on this.

If there is no "feature request" repo yet ... create one. It's worth it, believe you me.    I have more suggestions, and I am just one of many, who are thinking useful thoughts about your company.

**Comment by mosesn** [comment]
There isn't a repo, sorry!  Please follow up with Twitter support.

**Comment by drandreaskrueger** [comment]
I cannot. Because there is no Twitter support. Look at this:

1. [Contact us](https://help.twitter.com/en/contact-us) --> 3 topics, none fits
2. view all support topics --> https://help.twitter.com/forms. --> 27 topics, none fits.

You really want a "feature request" repo ...

**Comment by drandreaskrueger** [comment]
What about this: https://github.com/tweepy/tweepy/issues/1291  ?

If there is really no twitter API call for that, then everyone who still wants to get that information ... must do 3200 API.search calls [q=t.id for t in _all_my_recent_tweets] - and each possibly with paging calls. 

That is not efficient, especially not for the twitter servers, right?

**Comment by drandreaskrueger** [comment]
I have asked the question here now:

https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs/suggestions/39046141-multilingual-accounts-language-chooser-only-engl
