### ISSUE TITLE
util.Eval's class loader should be configurable

### ISSUE THREAD

**Issue by mkonicek** [twitter/util#29]
util.Eval has an issue in when used in environments with custom class loaders (such as in Play framework).

We have a set of libraries using util.Eval and we are using those libraries in a Play application. Basically, there are two class loaders in action at the same time.

While `new Eval().apply[AnyRef](configFileContents)` correctly loads a `MyConfig` object, that object can't be casted to `MyConfig` inside the Play app because it's been loaded using a different class loader than the one Play uses.

The problem is on lines [470 and 487 of Eval.scala](https://github.com/twitter/util/blob/master/util-eval/src/main/scala/com/twitter/util/Eval.scala#L470).

If those lines could be changed to

`classLoader = new AbstractFileClassLoader(target, baseClassLoader)`

where `baseClassLoader` is an overridable method (or a constructor argument, whichever you prefer), that would be great!

**Comment by vkostyukov** [comment]
Hi @mkonicek! Hope you're doing great: it's been three years since you filed this issue.

Anyways, I decided to let you know that we've deprecated `Eval` and not planning to improve it. Sorry for such a long delay.

**Comment by mkonicek** [comment]
Good to know @vkostyukov :)

**Comment by EugenCepoi** [comment]
Is there any recommended replacement for Eval? More precisely if one wants to compile src code to an output file?

**Comment by kevinoliver** [comment]
@EugenCepoi there must be better suggestions than this, but you could fork util-eval from before we removed it and then use that.

**Comment by EugenCepoi** [comment]
Hehe indeed though that's something I'd rather avoid :) So when the library got deprecated it wasn't in favor of a better alternative? It seems that I could directly use scala.tools.nsc.Global to achieve what I want, but in the end that's what util-eval was doing.

**Comment by kevinoliver** [comment]
Right. It was being primarily used for configuration at Twitter and we felt there were ample other means to do configuration without compiling Scala.
