### ISSUE TITLE
Bad link - 404 Not Found - in readme.md: https://twitter.github.com/util

### ISSUE THREAD

**Issue by MrCull** [twitter/util#294]
**Describe the bug**

Bad link - 404 Not Found - in readme.md:
https://twitter.github.com/util

**To Reproduce**
![image](https://user-images.githubusercontent.com/16634034/130350468-dc966f76-055e-46a8-a6b1-e0f3ac8517f4.png)

![image](https://user-images.githubusercontent.com/16634034/130350477-6d84e270-f64d-4c25-9238-f6772d58ae52.png)

**Expected behavior**

The 404 extra info suggest this should be:
https://twitter.github.io/

But than then redirects to: https://opensource.twitter.dev/

So I'm not sure that the link should point to

**Screenshots**
See above

**Environment**
N/A

**Additional context**

Issue found using tool: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

**Comment by cacoco** [comment]
@MrCull thanks for the issue. I think this just needs to be updated to the correct github.io address since GitHub stopped redirecting github.com recently: https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/.

**Comment by cacoco** [comment]
I believe the README has been updated. Closing this now. Thanks again!
