### ISSUE TITLE
Time.nanoTimeOffset

### ISSUE THREAD

**Issue by hoffrocket** [twitter/util#30]
https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Time.scala#L42

I don't think it's safe to statically cache the offset for long running apps.  The system time will likely change due to ntpd or whatever  and then the offset won't reflect those changes.

**Comment by vkostyukov** [comment]
`Time.nanonTimeOffset` [is deprecated](https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/util/Time.scala#L328) since 5.4.0. Closing this.
