### ISSUE TITLE
FutureTransformer (and other Java-friendly APIs?) needs @throws annotations

### ISSUE THREAD

**Issue by alexeyr** [twitter/util#40]
Scaladoc says it's allowed to throw exceptions from `FutureTransformer.map/flatMap/handle/rescue`, but since they aren't annotated with `@throws` checked exceptions can't be thrown from implementations. In this particular case there is a workaround with calling `super.handle(throwable)` instead of `throw throwable`, but it's a bit ugly.

**Comment by luciferous** [comment]
That makes sense to me. Would you like to submit a PR? If we move fast enough we can get this into the next release.

**Comment by luciferous** [comment]
Makes sense to me. Want to submit a PR? If we move fast enough we can get it into the next release.

**Comment by alexeyr** [comment]
OK, Two considerations:

1. Can `FutureEventListener` throw exceptions as well?
2. Is there other "Java-friendly API" in addition to `FutureTransformer` and `FutureEventListener`?

**Comment by luciferous** [comment]
Ok, trying to understand this better. Why throw when a Future.exception(exc) can be returned instead?

**Comment by alexeyr** [comment]
It can't be returned from `map` or `handle`.

**Comment by luciferous** [comment]
Why not use flatMap in instances when you might want to throw instead of map. And, for handle why not use transform?

**Comment by alexeyr** [comment]
> Why not use flatMap in instances when you might want to throw instead of map.

Yes, that's an option.

> And, for handle why not use transform?

Better would be to override `rescue`, actually.

Yes, it's probably unnecessary. Though it might be useful to document in ScalaDoc.

**Comment by luciferous** [comment]
That's a good point. It just seems against the "style" to throw exceptions in these closures, even though they do get converted to Futures.

**Comment by mosesn** [comment]
@alexeyr I agree that it makes sense to add a note in the scaladoc.  I'll add it internally and close this issue once I've done it.

**Comment by mosesn** [comment]
This was fixed here: https://github.com/twitter/util/commit/731175c269b52dd1e1238906c47ca05eaaed7306.  Thanks @alexeyr!
