### ISSUE TITLE
util-cache

### ISSUE THREAD

**Issue by sritchie** [twitter/util#46]
We should create a util-cache project and move `ImmutableLRU.scala` and

https://github.com/twitter/finagle/blob/master/finagle-core/src/main/scala/com/twitter/finagle/util/Cache.scala

over.

**Comment by vkostyukov** [comment]
There is already [`util-cache`](https://github.com/twitter/util/tree/master/util-cache/src/main/scala/com/twitter/cache) project. Although, it might be a good idea to move Finagle's cache there.

**Comment by vkostyukov** [comment]
We had an internal discussion and decided to not publish the Finagle's cache in utils but keep it private.
