### ISSUE TITLE
setReadLength on ThriftCodec

### ISSUE THREAD

**Issue by sritchie** [twitter/util#47]
Once we upgrade to Thrift 0.7.0, we can prevent the TProtocol from allocating huge amounts of memory by setting a read length limit:

```scala
override def invert(bytes: Array[Byte]) = {
    val obj = prototype.deepCopy
    val stream = new ByteArrayInputStream(bytes)
    val protocol = factory.getProtocol(new TIOStreamTransport(stream))
    // set upper bound on bytes available so that protocol does not try
    // to allocate and read large amounts of data in case of corrupt input
    protocol.setReadLength(bytes.length)
    obj.read(protocol)
    obj.asInstanceOf[T]
  }
```

**Comment by mosesn** [comment]
@sritchie we eventually ended up doing this internally, but yeah, this is hard without moving to a newer version of thrift.  Not sure we have the bandwidth to do it now, but we'll look into it.  util doesn't have anything to do with thrift though (I think), so I'm closing this ticket for now.
