### ISSUE TITLE
util-eval: Question about classpath in executable jar

### ISSUE THREAD

**Issue by btd** [twitter/util#71]
Hello.

At https://github.com/twitter/util/blob/master/util-eval/src/main/scala/com/twitter/util/Eval.scala#L338 it uses assumption that executable jar have just one, but on my debian server with last oracle jdk i have such class path:

List(List(/opt/staging/webapp/webapp/dist/webapp_2.10-0.1.jar, /opt/staging/webapp/newrelic/newrelic.jar), List(/usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/localedata.jar, /usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/sunpkcs11.jar, /usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/dnsns.jar, /usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/sunjce_provider.jar, /usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/zipfs.jar, /usr/lib/jvm/j2sdk1.7-oracle/jre/lib/ext/sunec.jar))

I want to point that java agent (-javaagent) also in classpath - of course mentioned assumption is wrong. 
Because of this my app could not have access in Eval to other jars. 

Could you advise something to this?

**Comment by vkostyukov** [comment]
Hi @btd! Thanks for submitting the issue!

As @stevegury mentioned, we're in the middle of deprecating (removing) `util-eval` so we're not going to improve it anyways. Thus, I think it's reasonble to close this issue. 

PS: Feel free to open a PR with the fix: we're happy to accept it.
