### ISSUE TITLE
Compiler issue with Futures

### ISSUE THREAD

**Issue by pequalsnp** [twitter/util#77]
I'm seeing some strange behavior in scala 2.10.2 with Future.

Welcome to Scala version 2.10.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_40).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.twitter.util.Future
import com.twitter.util.Future
               ^

scala> def a(default: Int, f: Future[Int]) = {
     | f handle { case _ => default }
     | }
a: (default: Int, f: com.twitter.util.Future[Int])com.twitter.util.Future[Any]

scala> def a(default: Int, f: Future[Int]): Future[Int] = {
     | f handle { case _ => default }
     | }
<console>:9: error: type mismatch;
 found   : A1 => B1
 required: Int
       f handle { case _ => default }

scala> def a(defaultValue: Int, f: Future[Int]): Future[Int] = {
     | f handle { case _ => defaultValue }
     | }
a: (defaultValue: Int, f: com.twitter.util.Future[Int])com.twitter.util.Future[Int]

Same test in 2.9.2 compiles without error.

**Comment by luciferous** [comment]
@pequalsnp https://github.com/scala/scala/blob/2.11.x/src/reflect/scala/reflect/internal/StdNames.scala#L1099
