### ISSUE TITLE
Any docs for util-zk?

### ISSUE THREAD

**Issue by devth** [twitter/util#81]

**Comment by thefourtheye** [comment]
@mosesn Will there be no tutorial on how to use it? How does a beginner use it? Throwing scala-docs at them is exactly the same as giving nothing.

**Comment by mosesn** [comment]
@thefourtheye unfortunately, we haven't had a chance to work on docs for util-zk.  However, a great way to contribute back to the community is to improve docs where you see that they could use some improvement!

**Comment by thefourtheye** [comment]
I have written code by going through the util-zk code. Do you have specific doc system in mind or just readme.md? I can send in a PR sometime tomorrow or the day after.

**Comment by mosesn** [comment]
I'd say either ReST or Markdown would both be great, whichever you prefer.  Let us know if you need any help from us :+1:
