### ISSUE TITLE
Upgrade ZooKeeper dependency to latest 3.4

### ISSUE THREAD

**Issue by sslavic** [twitter/util#94]
Various Twitter projects, including util modules still depend on ZooKeeper 3.3 even though ZooKeeper 3.4 is avilable since December 2011.
Please consider upgrading.

**Comment by vkostyukov** [comment]
It's [3.4.6](https://github.com/twitter/util/blob/develop/project/Build.scala#L12) already, which is the current stable version. I think this might be closed.
