### ISSUE TITLE
Future deadlock 

### ISSUE THREAD

**Issue by MansurAshraf** [twitter/util#98]
Hi,

I am working on upgrading [storehaushaus-kafka](https://github.com/twitter/storehaus) to work with Kafka 0.8.+. One of the issue I am running into is that Kafka 0.8 has introduced some blocking operations and when these operation get called inside a Future/FuturePool they end up in intermittent deadlocks. In particular [this](https://github.com/apache/kafka/blob/0.8.1/core/src/main/scala/kafka/producer/Producer.scala#L71) snippet of code is deadlocking when wrapped inside a  [Future](https://github.com/twitter/storehaus/blob/develop/storehaus-kafka/src/main/scala/com/twitter/storehaus/kafka/KafkaStore.scala#L48)

```
def send(messages: KeyedMessage[K,V]*) {
    lock synchronized {
      if (hasShutdown.get)
        throw new ProducerClosedException
      recordStats(messages)
      sync match {
        case true => eventHandler.handle(messages)
        case false => asyncSend(messages)
      }
    }
  }
```

Is there anything that can be done to prevent getting into deadlock? or the only option is to ask Kafka team to not use synchronize block in their api?
Thanks

**Comment by mosesn** [comment]
Looks like @benfradet can't reproduce this issue in https://github.com/twitter/storehaus/issues/233, so I'm going to trust him and mark this as fixed.  Probably we fixed this by accident somewhere down the line =).
